spring:
  application:
    name: spring-ai-alibaba
  ai:
    dashscope:
      # 你的阿里云 DashScope API Key，这里配置环境变量
      api-key: ${AI_DASHSCOPE_API_KEY:default-key}
      chat:
        options:
          model: qwen3-max
# 日志级别
logging:
  level:
    com.alibaba.cloud.ai: DEBUG